### ISSUE TITLE
Adjsut field width

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#20]
[問題集](https://github.com/ARJhe/odoo11/issues/22)
--
- **我想達成的效果：**
縮短或伸長form view的欄位寬度，如下圖

![marty-mcfly](https://i.imgur.com/gu0ESoX.png)

- **目前的寫法：**
在該view 插入css

.xml
```xml
        <!--css-->
        <template id="assets_backend" inherit_id="web.assets_backend">
            <xpath expr="." position="inside">
                <link href="/yc_root/static/src/css/cssfile.css" rel="stylesheet"/>
            </xpath>
        </template>
```
.css
```css
.o_input.ui-autocomplete-input#o_field_input_34,#o_field_input_36,#o_field_input_38,#o_field_input_40{
    width:60px;
}
```

**註：**
在xml檔直接賦予 field class name 並修改css沒有作用，
這4個欄位經過開發人員工具查到class及id為，
```html
<input class="o_input ui-autocomplete-input" id="o_field_input_34,36,38,40">
```

- **目前問題：**
 欄位id 在不同record會變，換一筆紀錄css就失去作用。

- **延伸：**
有兩個版面以上的view要去做css 或 javascript的插入會出現問題，該如何解決?
